---
title: "Finance and the biosphere - seminar 3"
layout: post
output:
  pdf_document:
    latex_engine: xelatex
    toc: true
    toc_depth: 4
    number_sections: true
  md_document:
    dev: png
    toc: yes
    toc_depth: 4
  html_document:
    number_sections: yes
    theme: default
    toc: yes
    toc_depth: 4
  word_document:
    reference_docx: template.docx
category: [real-world-economics, finance-sustainability]
tagline: "crash-course"
tags: [finance, biosphere, sustainability, seminar]
bibliography: PostDocKVA2.bib
---
{% include JB/setup %}

# Price volatility and financial markets - current debates and implications

Speakers: Christopher L. Gilbert, Johns Hopkins University, Italy
          Naomi Hossain, Institute of Development Studies (IDS), Oxfam, UK

Venue: Stockholm School of Economics, MISU program


<br><br>

------

------

<br><br>

#Introduction

**By Victor Galaz**

Context - Anthropocene and the relatively unstudied part of the system

Futures market: Wall STreet's thirst for market

Topics: Food prices and price volatility

Is volatility the new normal - World Economics Forum

<br><br>

-------

<br><br>


#Food prices, food price volatility and the financialization of agricultural futures markets

christopher.gilbert [at] jhu.edu


##Food price background

* **Relative food price levels** The relative price of food compared to other goods. The relative price is decreasing over time from 1970 to around 2000 wherefrom prices stabilize and slowly start to increase. Most recently this trend looks to have been reversed since 2007 or 2012.

* **Supply and deman for food** The demand curve has shifted to the right as a result of income growth, particularly in Asia. The supply curve has shifted up du to higher input prices on particularly fertilizer pulus as a slowdown in yield growth.

* **Volatility** Food price volatility calculated as the annualized intrayear standard deviation of month-on-month returns show little trend over the long run (1970-2012) for Grains, Vegetable Oils and Softs.

* **Volatility in 2008 and 2009-2010** 2008 (09-10) are outliers in the recent time period. Intra-year volatility is volatile over the years.

* **Price levels** While volatility has shown little trend, price levels have. Food prices have mainly increased since 2000 to 2014.

* **OECD price forecasts 2014-2023** Meat prices and dairies prices are predicted to increase by the OECD, while lower tropic levels are predicted to slightly decrease. Note large error margins.

<br><br>

##Financialization

* Financial agents/operators on the food commodity market have increased over time.

### Types of financial operators

* **Index-based investors** aim to track the returns on one or other ajor tradable commodity futures price index. They claim to be motivated by profolio diversification concerns and regard commodity futures as an asset class similar to equities, bonds and real estate. They trade in avery way from traditional non-commercials ("speculators"). tend to be long-term invetsors and have long holding periods. Roll as contracts approach expiration. Than's in comparison to traditional investors who tend to hold a subset of commodities and invest for short or long periods.

* **Did index trading move commodity futures prices?** Assertion that index investors like hedge fund managers did drive food price levels in 2008. Referral to senate testimony by hedge fund manager.

* **Index weights** The impact of index investors are more likely to be evident on the energy and metals markets.

* **Agricultural futures contracts** The period of most rapid growth in index investment predates the Special Call data in 2007 and 2008 in the US.

* **Granger causality tests from the index investment to commodity prices** Granger causality tests are significant for food, not beverages, agricultural raw materials, metals and minerals, non-energy index, brent crude oil. 

<br><br>

## Bubbles

* Were grains and oilseeds in a bubble trajectory in 2007-08? Tests applied on US prices.

* **Behavioral and rational bubble theory** Behavioral economists emphasize return chasing, herding, extrapolation and over-optimism on the part of retails ivestors. The mainstram account of bubbles rests on the view that finance theory gives a good account of the relationship between asset return, but only a weak account of asset values.

* **Testing for bubbles** Using the Philiips, Shi and Yu (PSY, 2013) procedure which has now become standard in this literuatere. ADF-tests.

* **PSY test results** Wheat, Corn and Soybeans all show econometric evidence of bubbles from the summer of 2007 to the summer of 2008. I.e. and explosive behavior. Crude oil also shows a bubble, slightly later, in the summer of 2008. Causal link in investor behaviour?

* Backward SADF test sequence indentifies a bubble in the index investment series between 2007 and 2008.

<br><br>

## Conclusions

* Food price commodity movements sin 2007-08 were exceptional, including wrt volatitlity.

* A rightward shift in the demand curve is suggested as a fundamental dirver for this change.

* Financial actiors, particularly index investors, played a role in impounding the perceoption of a changed fundamental environment into prices.

* Index investment in food commodites may have been instrmental in generating excessively high prices. Index investors may not have been the major driver, but may hae exacerbated the trend.


<br><br>

------

<br><br>


# Squeezed and angry - finding from research into ... volatility

*Naomi Hossain, Institute of Development Studies*

* Two projects:

    * Life in a Time of Food Price Volatility
    
    * Food riots and Food rights


## Motivations and aims

* FAO food price indices increased rapidly twice between 2008 and 2011 and then slowly have begun to taper off since 2011.

<br><br>

## Approach

* Research partners in 10 countries and with Oxfam GB.

* Global and national food price tracking.

* Qualitive research in 23 communities, ca. 250 households.

* Integrated national poverty / food security data analysis.

* Focus on neglected social dimensions of impact

    * Subjective and relational wellbeing
    
    * Unpaid care work
    
    * Informal social protection
    
    * Special themes - future farmers, accountability, fast food and fake food


<br><br>

## Methodology from global to local and back again

* **The boat** Macro conditions (gloal Food Price Value/Volatility) -> Micro conditions -> Micro-outcomes -> Macro outcomes


<br><br>

## Findings

<br><br>

### Prices and wages

* 2012 spike did not transmit to local communities but food prices still rose. Uncertainty meant people could not budet, save, plan. effects of price riesses cumulative: a squeeze not a shock.

* 2012, many wages nominally up, but not by enough; by 2013, wages mostly adjusting.

    * Partly because women doing more paid work - crowding out unpaid care
    
    * And new and more precariuos jobs, migration.

<br><br>

### Who wants to be a farmer

* You people see smallholder farming as occupation of last resort - formal sector jobs preferred.

* Tough, risky and unrewarding.

* Inaccessible because of land, capital, input needs.

* Appealing if modernised and supported / subsidized.


<br><br>

### Changing food habits

* People cope with high prices with usual coping strategies - cutting down, cutting out, less diverse & cheaper food.

* Rising concerns about food safety, linked to higher prices.

* Growing evidence of convenience foods

    * Local vendors
    
    * Commercial processed foods

* Children's snacking

* Food cultures and customs

* Nutritional quality


<br><br>


### Social protection and the right to food

* Common sense of right to food as natural and social backed by faith, custom and membership of community.

* People know their legal human rights.

* **Formal state support for provisioning**

* **On food security programmes** - Standards are low - discriminatory and discretionary.

<br><br>


## The political response to food price increases - "Them belly full (but we hungry)"

* Political repsonses to food and fuel riots and food rights.


* Food rights strugggles in Bangladesh, India, Kenya and Mozambique

* "People just don't go out and burn things because they are hungry, they are also linked to the moral economy"

* Food rights movements (Kenya and India)

* Alleged food riots (Bangladesh and Mozambique)


<br><br>


### The moral economy (or "ideas about how food markets should work") in the 21st century

* The prices spikes were the trigger of relase of existing and underlying tensions.

* Protection of minimal rights to food are foundational for the social contract.


<br><br>

### Final thoughts


* Food price levels in 2007-12 changed the relation ship people have to food

* **Resources - reports**

    * Life in a time of food price volatiliity

    * Food riots and food rights: the moral and political econoomy of accountability ofr hunger



<br><br>

-------

<br><br>

# Discussion

* Christopher: Signed up member to the Washington Consensus

* Christoph Guell - countries should combine trade and stocks to prevent food price induced crises

* Drivers of food price costs - **role of fertilizer** - role of kartel like structure in fertilizer supply.

* Christopher: Fertilizer is an oligopolistic market - it is a significant part of the story, but not the dominant.

* The urban bias story - urban vs. rural

    * There is no longer "*anything wrong*"" with urban bias due to urbanization in developing countries
    
    * A lot of the urban inhabitants have rural ties - they may be able to cope
    
    * Diets between urban and rural areas differ
    
* How does food and health go together?

    * It looked like the food price spikes resulted in highly-processed foods entering the market changing the paradigm from undernutrition to malnutrition.

    * Naomi: A lot of effects on mental health - people got stressed.

    * Christopher: Effects on public health through effects on fetal development through malnutrition in the vomb. Nice tie between economics and public health.

* Children investment fund foundation

    * Role of investors in supporting groups seeking legal complaints wrt food rights?


* Strucutral shift in the demand side - what is the explanation for the temporal lag in adjustement on the supply side

    * Recent paper by Paul Collier and one other. Small-scale farming will not solve the criss.
    
    * Agro-ecological perspective - Camilla Tumen at IAD - increasing yields and productive possible with increasing fertilizer and other aspects of intensity.
    
    * Christopher: There has been a lot of supply response in particular in the US. In Africa it is difficult to think about the change in response. Takes Paul Collier statement with a grain of salt. Small-holder productivity is still important.
    
* Q: Role of food waste habits on the consumption side

    * Christopher: There is a lot of waste, but it is expensive to do something about it. A lot of waste comes through waste between harvesting and consumption (e.g. from loss during storage). Dealing with that is compliated because good storage is expensive.


* Q: Three categories - on which do you differ?

    1. Price levels
    
    2. What correlates to what - causation
    
    3. The normative directions of the discourses

    * Christopher - I think we complement each other rather than disagree with each other.
    
    * Naomi - causality is hard. Normative directions may be where we differ the most. Naomi much less trust in the market after 2008 compared to before.


<br><br>



------

------

<br><br>

# REFERENCES

The following literature was cited

