---
title: "Notes Garry meeting"
author: "Peter Søgaard Jørgensen"
date: "Friday, April 24, 2015"
output: html_document
---




#### Migration flows - capital flows

* captial in, migration in

* capital out, migration out

* capital in, migration out

* capital out, migration in

----- 

### Notes for RWE outline

#### Inequality

* Unequal localities - mental health and stress for rising in the social hierarchy

    * Tim Jackson - social hierarchy
    
    * Spirit level
    
    * *Conspicuous consumption* - Consuming to be seen and get status.
    
        * Thorstein Vebleen
        
        * Veblen goods

* Unequal nations - less government investment in public health

    * Picketty - weatlh 


* Quality of democracy

    * Median voter theorem
    
    * Regulatory capture
    
        * Case: Endangered Species Act - strong, but not implemented, because state governments do not fund it.
        
    * Political economy


* Co-production - what happens when scientists collaborate

    * Challenges of co-production
    
    * How do you think of having socially good processes, without being over-normative.
    

* Concentrated media

    * Australia - media owned by coal ownership
    
    * Employment in PR industry versus journalism
    
    * Role of large media corportations in demochratic sustainable transitions
    
        * Communication of information about non-empowering information/news
        
            * e.g. 
            

* Global inequality - Historical political ecology

    * Henrik on Soviet Union and regime shifts
    
    * Mark Davis - late Victorian-holocausts
    
        * El-Nino, famines, and the making of the third world
        
    * India: Climate shocks used to be normal in India - colonialism blocked institutional adaptation - Raj - modern society - 
    
    * Luis et al. - mass die-offs of native americans to European settlement - onset of the Anthropocene
    
    * Shock doctrine and the socio-ecological as well as macroeconomic consequences today




        
        
http://www.afdb.org/en/blogs/integrating-africa/post/african-regional-integration-and-the-fight-against-illicit-financial-flows-12898/

http://www.gfintegrity.org/storage/gfip/documents/reports/gfi_africareport_web.pdf

http://www.unodc.org/documents/data-and-analysis/Studies/Illicit_financial_flows_2011_web.pdf

https://openknowledge.worldbank.org/bitstream/handle/10986/6719/wps4618.pdf?sequence=1

http://www.gfintegrity.org/reports/

http://www.gfintegrity.org/

https://books.google.se/books?hl=en&lr=&id=CCwqWOvf9dQC&oi=fnd&pg=PR5&dq=human+trafficking+illicit+financial+flows&ots=Vm5pNT9V_4&sig=0uoR07JZjcDnayaBLfpoZ1PL9EM&redir_esc=y#v=onepage&q=human%20trafficking%20illicit%20financial%20flows&f=false

http://www.econstor.eu/bitstream/10419/52839/1/376632771.pdf

http://natlex.ilo.ch/wcmsp5/groups/public/---ed_norm/---declaration/documents/publication/wcms_081931.pdf

http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2528587

http://www.jstor.org/discover/10.2307/1123280?uid=3738984&uid=2&uid=4&sid=21106131267781

http://scholarship.law.gwu.edu/cgi/viewcontent.cgi?article=1928&context=faculty_publications

http://faculty.haas.berkeley.edu/Dalbo/Regulatory_Capture_Published.pdf





---

* financial innovation as a roving bandits strategy

    * is financial innvoation a strategy for escaping regulation
    
    * black and grey markets
    
        * money laundering - tax havens
    
    * "black/deviatnt globalization (book)"
    
        * using globalization to evade prosecution
    
        * cross-border crime as a business to benefit from administrative
    
    * illegal waste dumbing in Italy, starting out as legal waste exports in Germany
    
    
    * Gomorrah movie

* illicit financial flows -
    
    * **Estimate size of flows**
    
    * **Find good cases**
    
        * Illicit flows from China (to Garry's hometown)
        
            * Partially off the books businesses moving capital out of country to obscure tracking.
            
            * Main investors in China are global tax havens.
        
        * "Narko states" - e.g. Colombia, Mexico
        
            * Effects on land use change dynamiscs
            
                * E.g. Colombia, spraying fields will generate new areas with deforestation for coca plantations.
    
    * [Global Financial Integrity](http://www.gfintegrity.org/)
    
        * [Global Illicit Financial Flows Reports](http://www.gfintegrity.org/reports/)
    
    * drugs
    
        * Cocaine production World Bank report - What Do We Know
    
    * human trafficking (probably treat separate from drugs)
    
        * a problem and a solution
        
            * new people in countries as source of conflict
            
                * ethnic diversity as a source of conflict or a sign of different cultures
                
                * 
            
            * new people in countries as a source of innovation (*REFS from economic geography*)
            
                * new economic ventures started up by immigrants
                
                * immigrants in canadian households earning more than native-born canadians
                
                * interlinked-chains of skilled migrants between coupled bilateral systems
                
    

* family financial networks

    * Hawala

    * Informal Transfer Systems - IMF report on Hawala
    
    * framed under a teleccoupled financial 

* **References**

    * ***Do international migration and remittances reduce poverty in developing countries***

    * Remittances, financial development and growth - **Highly cited paper**

    * Evaluating the Economic Impact of International Remittances on Developing Countries

* possible structuring

    * global markets and on the ground effects
    
        * financial flows
    
    * local networks and the global impact and context 


        * most illicit flows
        

#### Globalization


actors | white (licit) | grey | black (illicit) |
-------|---------------|-------|-------|
finance | banks, bonds |  | money laundering |
global actors | direct land investment  | |narco / arms / mafias / range |
individual agens | remittances | |illegal migrants & "evaders of the state"|


---


* Berkes

* Kate Brown - development geography - adaptation to climate change

--

* Kates

* Billy Lee Turner

* Hal Mooney


---

* Daniel


* Deeper integration with economic and social sciences

    * Going away from individualism, having a more rich view of how societies function - corruption - brutality - goodness - norms - war & conflict (blind spots - myopias - cognitive disonance - understand the world and see the seeds of good) - decision making / participatory stuff


* Advanced economic modelling (maybe not for the paper)

    * Game theory - Chaos - Buzz Braug -
    
    *


* Socio-ecological consequences of financial and market dynamics

    * The principal agent problem
    
        * What are employees evaluated for and what is the goal of the institution
        

* National bankruptcies - socio-ecological consequences of economic shocks

      * Asian financial crisis
      
      * Latin American crises - 
      
          * Argentina - rangelands
          
          * Brazil - forest dynamics

      * Somalia - cautionary tale of socio-ecological drivers of piracy in a economically and democratically collapsed state
      

---

Key guideline for the moore controversial bits - looking at the empirical side of things

Future perspectives - how can sustainability science go on from here in interacting with a broad set of large scale/real world socio-economic issues

Meeting with Daniel and Anne Sophie

Potential editors

  * Neil Adger & Kate Brown


