---
title: "Real world economics new outline"
category: real-world-economics
date: "Thursday, May 28, 2015"
output:
  html_document:
    number_sections: yes
    theme: default
    toc: yes
    toc_depth: 3
  md_document:
    dev: png
    toc: yes
    toc_depth: 3
  pdf_document:
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 3
  word_document:
    reference_docx: template.docx
layout: post
tagline: Outlining an ms
tags:
- outline
- real world economics
- economics
- sustainability
- sustainability science
bibliography: PostDocKVA2.bib
---
{% include JB/setup %}





# MS outline

## Introduction argument

1. Sustainability science is evolving and must integrate advances from the interdisciplinary as well as the disciplinary realm

2. Globalization and financialization of the global economy means sustainability science cannot ignore, but must fully integrate with real world economic phenomena of the anthropocene. These phenomena are likely to play an increasing role in linking socio-ecological systems across the globe and the likelihood of communities to undertake a sustainability transformation. Integrating with these topics will bring sustainabililty science closer to realizing its multidsciplinary vision and improve the relevance of research findings for understanding global dynamics and sustainable development including societal transformations for sustainability.
    
3. Based on an overview of important economic phenomena of the anthropocene and their socio-ecological relevance, we' provide a simple conceptual framework to understand the socio-ecological dynamics in the financialized global economy. This framework is illustrated with examples of areas that need rapid integration in order to inform the global sustainability transition.

-------

## Aims

- The manuscript aims to advance the study of the sustainability transition of the global socio-ecological system through integration of economic phenomena of the anthropocene (so called "real world economics")

- The manuscript will highlight examples from generally overlooked economic phenomena in need of integration (so called blind spots) and search for three characteristics within them:

    - the degree of relevance of blind spots for the sustainability transition illustrated by their socio-environmental consequences.

    - examples of successful integration from within this generally overlooked phenomena into sustainability science (so called bright spots of integration)

    - opportunities for integrating advances (especially empirical) from the more disciplinary research fields into sustainability science (so called disciplinary bright spots, whether socio-environmental or not yet environmental)
    
- Finally, the manuscript will based on the identified areas and highlighted examples end by giving suggestions for how to advance integration of blind spots into sustainability science in the future, e.g. through increased outreach to disciplinary communities.

-------

## Type of manuscript

- Perspective and opinion manuscript (e.g. ~ 2000-4000 words).

- Based on selective review of chosen topics in sustainability science journals and the disciplinary literature.

- Combining overview of advances by empirical case studies and introduction of a conceptual framework for integration in sustainability science.

- Example target journals:
    1. PNAS
        - Perspective (varies in length e.g. between 1600-7000 words)
        - Contact editor with proposal
    2. Global environmental change (IF 6, no specific types of manuscripts)
    3. Sustainability science (IF 3.37, types: article, review, overview)
    4. Ecology and society (IF 2.669)
    5. Anthropocene or anthropocene review
    6. Frontiers in ecology and environment (too ecological?)
    7. Bioscience (too ecological?)



-------

## Three suggested general blind spots and arguments for inclusion

- Unaccounted economic flows

    - While trade is now routinely seen as an economic activity that telecouples distant socio-environmental systems other, often unaccounted for, economic flows may be just as important telecouping agents - e.g. migrant remittances, illicit drugs, arms and wildlife trade.

- Financial dynamics and innovation

    - Financialization of global society is the most recent stage of the globalization process. It means that finance takes up a larger proportion of many national economies. Financial dynamics impacts socio-ecological dynamics far apart. At the same time what is the potential for innovation of financial instruments for sustainability.

- Democracy and inequality in the green transition

    - Inequality is back at levels of the beginning of the 20th century and has seen increased attention from disciplinary research since the great recession in 2008. Sustainability science could benefit by building on this increased focus from a wide variety of disciplinary research fields.

----------

## Suggested focal areas within the general blind spots

- Socio-environmental effects (such as telecoupling) from unaccounted economic flows
    - Cases:
    - Migration and remittance flows
        - Remittances and institutional innovation and online banking, e.g. micro loans
    - Drug, arms and illegal wildlife trade


- Socio-environmental effects of financial investor behavior and financial innovation

    - Financial dynamics:
        - Cases:
        - Role of index investors in the food price spike in 2008/2009, 2011/2012 and contribution to the Arab uprisings
            - Empirical econometric evidence suggesting investors contributed to driving price increases
        - Socio-environmental effects of "keystone"" economic actors in the global network of coorporations
            - Marine keystone actors
            - Determinants of fertilizer prizes and environmental consequences
        - Socio-environmental effects of sovereign defaults
            - Still have to find clear cases here - EU crisis is one example wher suicides go up and well-being worsens while investment in e.g. shale gas goes up


    - Financial innovation as a doubled edged sword - regulatory escape or innovating for sustainability
        - Suggested cases:
        - Small scale financial instruments (micro-finance) - e.g. farmer insurance of crops
        - Effect of small scale regulatory changes - e.g. World Bank reformed guidelines
        - New instruments with missing standards - e.g. Green Bonds market


- The green democractic transition in the anthropocene - effects of inequality and concentration of wealth
    - Cases:
    - Global context: Stalled global environmental negotiations and inequality - e.g. climate negotiations
    - National:
        - Voting behaviour of elected representatives in economies with high inequality
        - Regulators dilemma and regulatory capture in environmental regulation & enforcement - e.g. offshore drilling, wildlife protection act and others
        - Media ownership and coverage of the sustainability transition - are populations more aware about the transition in countries with more diverse media ownership?
    - Local: Inequality and mental health and well-being
        - Can poor mental health and well-being in e.g. competitive enviornments undermine a green transition? Is it a precondition for the green transition?
        - Cases: Whitehall I and II studies, public health and inequality research, biodiversity decline and inequality research 
        


----------


## Suggested co-authors (alphabetically) and suggested areas of attention

- Anne-Sophie (ties to economics)
- Daniel (especially migration and land systems)
- Garry (inqueality, good/bad anthropocene context)
- Peter (macro-socio-ecological perspective on all examples, coordinating the write up)

Also (if interested):

- Calle (keystone financial actors)
- Gretchen (natural capital and financial innovation)
- Victor and Cecilia (financial innovation)




<br><br>

----

----

<br><br>



# REFERENCES

No literature cited in this outline

